using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using System.Text;

namespace CallCentersRD_API.Services
{
    public class exportXls
    {

        public byte[] exportToExcel(List<Database.Entities.Auth.User> userList)
        {
            try
            {
                ////WorkBook wb = WorkBook.Load("XlsFile.xls");//Import .xls, .csv, or .tsv file
                ////wb.SaveAs("NewXlsxFile.xlsx");//Export as .xlsx file
                //WorkBook wb = WorkBook.Create();
                //wb.Metadata.Author = "Ronel Cruz Ceballos (RONEL.CRUZ.A8@GMAIL.COM)";
                //wb.Metadata.Title = "CallCentersRD";
                //WorkSheet ws1 = wb.CreateWorkSheet("Usuarios");
                ////WorkSheet ws2 = wb.CreateWorkSheet("Preguntas");
                //ws1["A1"].Value = "ID del usuario";                
                //ws1["B1"].Value = "Nombre del usuario";
                //ws1["C1"].Value = "Apellidos";
                //ws1["D1"].Value = "Correo Electronico";
                //ws1["E1"].Value = "Ultima fecha activo";
                //int index = 3;
                //foreach (Database.Entities.Auth.User user in userList)
                //{
                //    ws1["A"+index].Value = user.Id;
                //    ws1["B"+index].Value = user.Name;
                //    ws1["C"+index].Value = user.LastName;
                //    ws1["D"+index].Value = user.Email;
                //    ws1["E"+index].Value = user.lastLogin;
                //    index++;
                //}
                ////String filename = "CallCentersRD_Autogenerated_Files_" + DateTime.Now.ToString("dddd, dd MMMM yyyy").Replace(" ","_").Replace(",","") + ".xlsx";
                ////wb.SaveAs(filename);

                ////byte[] byteArray = File.ReadAllBytes(filename);
                //return wb.ToByteArray();


                //// Step 1: Create a DataSet, and put some sample data in it
                //DataSet ds = CreateSampleData();

                //// Step 2: Create the Excel .xlsx file
                //try
                //{
                //    CreateExcelFile.CreateExcelDocument(ds, "C:\\Sample.xlsx");
                //}
                //catch (Exception ex)
                //{
                //    MessageBox.Show("Couldn't create Excel file.\r\nException: " + ex.Message);
                //    return;
                //}





                //StringBuilder str = new StringBuilder();
                //str.Append("<table border=`" + "1px" + "`b>");
                //str.Append("<tr>");
                //str.Append("<td><b><font face=Arial Narrow size=3>FName</font></b></td>");
                //str.Append("<td><b><font face=Arial Narrow size=3>LName</font></b></td>");
                //str.Append("<td><b><font face=Arial Narrow size=3>Address</font></b></td>");
                //str.Append("</tr>");
                //foreach (Record val in obj)
                //{
                //    str.Append("<tr>");
                //    str.Append("<td><font face=Arial Narrow size=" + "14px" + ">" + val.FName.ToString() + "</font></td>");


                var memoryStream = new MemoryStream();

                using (ExcelPackage package = new ExcelPackage(memoryStream))
                {
                    ExcelWorksheet worksheet;
                    worksheet = package.Workbook.Worksheets.Add("xxx");

                    worksheet.Name = "jodon";

                    //for (int i = 0; i < 50; i++)
                    //{
                    //    worksheet.Cells[1, i + 1].Value = nameColumns[i];
                    //}

                    package.Save();
                }

                memoryStream.Position = 0;
                var contentType = "application/octet-stream";
                var fileName = "fileName.xlsx";
                 //File fff = new File(memoryStream, contentType, fileName);
                return memoryStream.ToArray();

            }
            catch (Exception e)
            {
                throw e;
                return null;
            }
        }
    }
}
